

```{r}
dados = read.csv("Churn.csv", sep = ";", na.strings="", stringsAsFactors=T)
head(dados)
summary(dados)
```
# Dar nome às colunas:

```{r}
colnames(dados) = c("Id", "Score", "Estado", "Gênero", "Idade", "Patrimônio", "Saldo", "Produtos", "TemCartaoCredito", "Ativo", "Salário", "Saiu")
head(dados)
```

Explorar dados, colunas categóricas:
```{r}
# Estados:
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")
# Gênero
counts = table(dados$Gênero)
barplot(counts, main="Gêneros", xlab="Gêneros")
```
Explorar colunas numéricas:
```{r}
# Score:
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
Idade:
```{r}
# Idade:
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
Saldos:
```{r}
# Saldos:
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```
```{r}
# Salário
summary(dados$Salário)
boxplot(dados$Salário)
hist(dados$Salário)
```
Valores faltantes (NAs):
```{r}
dados[!complete.cases(dados),]
```


```{r}
# Tratar salários:
summary(dados$Salário)
# Ver mediana:
median(dados$Salário,na.rm=T)
# Atribuir mediana a NAs:
dados[is.na(dados$Salário) ,]$Salário = median(dados$Salário, na.rm=T)
#Buscar NAs em salário para checar:
dados[!complete.cases(dados$Salário),]
```
Falta de padronização em gênero:
```{r}
# ver valores
unique(dados$Gênero)
summary(dados$Gênero)
# Transformar F em feminino M em masculino
dados[is.na(dados$Gênero) | dados$Gênero == "M",]$Gênero = "Masculino"
dados[dados$Gênero == "F" | dados$Gênero == "Fem",]$Gênero = "Feminino"
# ver resultado
summary(dados$Gênero)
# Remover levels não utilizados
dados$Gênero = factor(dados$Gênero)
# Vizualizar novamente
summary(dados$Gênero)
```
Idades fora do domínio:
```{r}
summary(dados$Idade)
# fora do domínio, ver idades anormais
dados[dados$Idade<0 | dados$Idade>110 , ]$Idade
# Não temos idades NAs
dados[is.na(dados$Idade),]
# Opção preencher com mediana
median(dados$Idade)
# Substituição
dados[dados$Idade<0 | dados$Idade>110 ,]$Idade = median(dados$Idade)
#Buscamos novamente idades anormais
dados[dados$Idade<0 | dados$Idade>110 ,]
summary(dados$Idade)
```
Dados duplicados:
```{r}
# Buscar duplicados pelo id:
x = dados[duplicated(dados$Id),]
x
# Excluir dados pelo Id:
dados = dados[-c(82),]
# Verificar novamente
x = dados[duplicated(dados$Id),]
x
summary(dados$Id)
```
Estado fora do domínio:
```{r}
# Fora do domínio - categórico
unique(dados$Estado)
summary(dados$Estado)
# Preencher com a moda RS
dados[!dados$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(dados$Estado)
# Removendo fatores não usados
dados$Estado = factor(dados$Estado)
# Visualizar novamente
summary(dados$Estado)
```
Outliers:
```{r}
# Criando um parâmetro com desvio padrão
desv = sd(dados$Salário, na.rm=T)
desv
dados[dados$Salário >= 2 *desv ,]$Salário
# Outra forma sem os NAs
boxplot(dados$Salário)
boxplot(dados$Salário, outline= F)
x = boxplot(dados$Salário)$out
x
# Atualizar todos para mediana
median(dados$Salário)
dados[dados$Salário >= 2 *desv , ]$Salário = median(dados$Salário)
# Checamos se sairam os outliers
dados[dados$Salário >= 2 *desv , ]$Salário
```
